/**
 * UniversalETLScreen.tsx
 * ──────────────────────
 * A single, highly reusable component that adapts to ANY module + business object
 * combination. Implements the 4-step ETL stepper:
 *   Extract/Upload -> Validate -> Preview -> Load to Oracle
 *
 * DRY: This ONE component handles every business object.
 * No separate files per object — just pass different props.
 */

import { useState, useCallback, useRef, useEffect } from 'react';
import {
  Upload, CheckCircle2, FileSpreadsheet, Loader2,
  ArrowLeft, AlertCircle, Rocket, X, FileUp, Download, FileText,
} from 'lucide-react';
import type {
  ModuleConfig,
  BusinessObject,
  DatabaseMappingSource,
  Entity,
  ExcelRow,
  MappingRule,
  ParsedWorkbookData,
} from '@/features/dataConversion/types';
import {
  buildAutoGeneratedMapping,
  buildDatContent,
  createEntitiesFromNames,
  downloadEntityArchive,
  parseWorkbookForConversion,
} from '@/features/dataConversion/workbook';
import { toast } from 'sonner';
import { dataConversionApi } from '@/services/api';

interface UniversalETLScreenProps {
  module: ModuleConfig;
  object: BusinessObject;
  onBack: () => void;
}

type ETLStep = 'upload' | 'validate' | 'load';
interface WorkbookSheetData {
  sheetName: string;
  rows: ExcelRow[];
}

const STEPS: { key: ETLStep; label: string; icon: typeof Upload }[] = [
  { key: 'upload', label: 'Extract / Upload', icon: Upload },
  { key: 'validate', label: 'Validate', icon: CheckCircle2 },
  { key: 'load', label: 'Load to Oracle', icon: Rocket },
];

function getDefaultEntityNames(object: BusinessObject): string[] {
  return object.defaultEntities && object.defaultEntities.length > 0
    ? object.defaultEntities
    : object.databaseMappings && object.databaseMappings.length > 0
      ? object.databaseMappings.map(mapping => mapping.entityName)
    : [object.label];
}

function collectWorkbookSheets(parsedWorkbook: ParsedWorkbookData): WorkbookSheetData[] {
  const seen = new Set<string>();
  const sheets: WorkbookSheetData[] = [];

  parsedWorkbook.entityNames.forEach(entityName => {
    const sheetName = parsedWorkbook.entityDataSheetNames[entityName] || entityName;
    if (!sheetName || seen.has(sheetName)) {
      return;
    }

    seen.add(sheetName);
    sheets.push({
      sheetName,
      rows: parsedWorkbook.excelData[entityName] || [],
    });
  });

  return sheets;
}

function findSheetForDatabaseEntity(
  entityName: string,
  sheets: WorkbookSheetData[],
  usedSheetNames: Set<string>,
): WorkbookSheetData | null {
  const availableSheets = sheets.filter(sheet => !usedSheetNames.has(sheet.sheetName));
  if (availableSheets.length === 0) {
    return null;
  }

  if (availableSheets.length === 1) {
    return availableSheets[0];
  }

  const normalizedEntityName = normalizeHeader(entityName);
  const exactMatch = availableSheets.find(sheet => normalizeHeader(sheet.sheetName) === normalizedEntityName);
  if (exactMatch) {
    return exactMatch;
  }

  const containsMatch = availableSheets.find(sheet => {
    const normalizedSheetName = normalizeHeader(sheet.sheetName);
    return normalizedSheetName.includes(normalizedEntityName) || normalizedEntityName.includes(normalizedSheetName);
  });

  return containsMatch ?? availableSheets[0];
}

function isApiErrorResponse<T>(value: T | { error: { message: string } }): value is { error: { message: string } } {
  return typeof value === 'object' && value !== null && !Array.isArray(value) && 'error' in value;
}

function normalizeHeader(value: unknown): string {
  return String(value ?? '')
    .trim()
    .toLowerCase()
    .replace(/[^a-z0-9]/g, '');
}

function getMissingMappedColumns(sheetData: ExcelRow[], sheetConfig: MappingRule[]): string[] {
  if (sheetData.length === 0) {
    return [];
  }

  const headerLookup = new Set(Object.keys(sheetData[0] ?? {}).map(normalizeHeader));

  return sheetConfig
    .filter(rule => {
      const columnOrder = typeof rule.ColumnOrder === 'string' ? rule.ColumnOrder.trim().toUpperCase() : '';
      return columnOrder.startsWith('B');
    })
    .filter(rule => {
      const hdlValue = String(rule.HDL ?? '').trim().toUpperCase();
      return hdlValue === '' || hdlValue === 'NULL';
    })
    .map(rule => typeof rule.InputColumnName === 'string' ? rule.InputColumnName.trim() : '')
    .filter(Boolean)
    .filter((columnName, index, allColumns) => allColumns.indexOf(columnName) === index)
    .filter(columnName => !headerLookup.has(normalizeHeader(columnName)));
}

function downloadTextFile(filename: string, content: string): void {
  const blob = new Blob([content], { type: 'text/plain;charset=utf-8' });
  const url = URL.createObjectURL(blob);
  const anchor = document.createElement('a');
  anchor.href = url;
  anchor.download = filename;
  document.body.appendChild(anchor);
  anchor.click();
  anchor.remove();
  URL.revokeObjectURL(url);
}


export function UniversalETLScreen({ module, object, onBack }: UniversalETLScreenProps) {
  const [currentStep, setCurrentStep] = useState<ETLStep>('upload');
  const [file, setFile] = useState<File | null>(null);
  const [isDragging, setIsDragging] = useState(false);
  const [isValidating, setIsValidating] = useState(false);
  const [validationResult, setValidationResult] = useState<'success' | 'error' | null>(null);
  const [validationErrors, setValidationErrors] = useState<string[]>([]);
  const [validationReportContent, setValidationReportContent] = useState('');
  const [totalRecords, setTotalRecords] = useState(0);
  const [passedRecords, setPassedRecords] = useState(0);
  const [excelData, setExcelData] = useState<Record<string, ExcelRow[]>>({});
  const [mappingConfigs, setMappingConfigs] = useState<Record<string, MappingRule[]>>({});
  const [entityDataSheetNames, setEntityDataSheetNames] = useState<Record<string, string>>({});
  const [entityTableNames, setEntityTableNames] = useState<Record<string, string>>({});
  const [dynamicEntities, setDynamicEntities] = useState<string[]>([]);
  const [preparedOutputByEntityId, setPreparedOutputByEntityId] = useState<Record<string, string>>({});
  const [activePreviewEntityId, setActivePreviewEntityId] = useState<string | null>(null);
  const [entities, setEntities] = useState<Entity[]>(() => createEntitiesFromNames(getDefaultEntityNames(object)));
  const fileInputRef = useRef<HTMLInputElement>(null);

  useEffect(() => {
    if (dynamicEntities.length > 0) {
      setEntities(createEntitiesFromNames(dynamicEntities));
    }
  }, [dynamicEntities]);

  const stepIndex = STEPS.findIndex(s => s.key === currentStep);
  const successPercentage = totalRecords > 0 ? Math.round((passedRecords / totalRecords) * 100) : 0;

  // ── Drag & Drop handlers ──
  const handleDragOver = useCallback((e: React.DragEvent) => {
    e.preventDefault();
    e.stopPropagation();
    setIsDragging(true);
  }, []);

  const handleDragLeave = useCallback((e: React.DragEvent) => {
    e.preventDefault();
    e.stopPropagation();
    setIsDragging(false);
  }, []);

  const handleDrop = useCallback((e: React.DragEvent) => {
    e.preventDefault();
    e.stopPropagation();
    setIsDragging(false);
    const dropped = e.dataTransfer.files[0];
    if (dropped && dropped.name.endsWith('.xlsx')) {
      setFile(dropped);
      setValidationResult(null);
      setValidationErrors([]);
    }
  }, []);

  const handleFileSelect = useCallback((e: React.ChangeEvent<HTMLInputElement>) => {
    const selected = e.target.files?.[0];
    if (selected && selected.name.endsWith('.xlsx')) {
      setFile(selected);
      setValidationResult(null);
      setValidationErrors([]);
    }
  }, []);

  const handleValidate = useCallback(async () => {
    if (!file) {
      toast.error('Please upload an Excel workbook first.');
      return;
    }

    setIsValidating(true);
    setCurrentStep('validate');
    setValidationResult(null);
    setValidationErrors([]);
    setValidationReportContent('');
    setTotalRecords(0);
    setPassedRecords(0);

    try {
      await new Promise(resolve => setTimeout(resolve, 350));

      const parsedWorkbook = await parseWorkbookForConversion(file, { allowDataOnly: true });
      const configuredDatabaseMappings: DatabaseMappingSource[] = object.databaseMappings ?? [];

      if (configuredDatabaseMappings.length > 0) {
        const workbookSheets = collectWorkbookSheets(parsedWorkbook);
        const usedSheetNames = new Set<string>();
        const issues: string[] = [];
        const reportLines: string[] = [
          'Validation Report',
          `Workbook: ${file.name}`,
          `Business Object: ${object.label}`,
          '',
        ];
        let computedTotalRecords = 0;
        let computedPassedRecords = 0;
        const effectiveExcelData: Record<string, ExcelRow[]> = {};
        const effectiveMappingConfigs: Record<string, MappingRule[]> = {};
        const effectiveDataSheetNames: Record<string, string> = {};
        const effectiveTableNames: Record<string, string> = {};

        for (const mappingSource of configuredDatabaseMappings) {
          const mappingResponse = await dataConversionApi.getEntityMapping(mappingSource.tableName);
          const matchedSheet = findSheetForDatabaseEntity(mappingSource.entityName, workbookSheets, usedSheetNames);
          const sheetData = matchedSheet?.rows ?? [];

          effectiveExcelData[mappingSource.entityName] = sheetData;
          effectiveDataSheetNames[mappingSource.entityName] = matchedSheet?.sheetName ?? '';
          effectiveTableNames[mappingSource.entityName] = mappingSource.tableName;

          reportLines.push(`Entity: ${mappingSource.entityName}`);
          reportLines.push(`Mapping Table: ${mappingSource.tableName}`);
          reportLines.push(`Data Sheet: ${matchedSheet?.sheetName ?? 'Not matched'}`);
          reportLines.push(`Rows Found: ${sheetData.length}`);

          if (isApiErrorResponse(mappingResponse)) {
            issues.push(`Mapping table "${mappingSource.tableName}" could not be loaded.`);
            reportLines.push('Status: Failed');
            reportLines.push(`Issue: ${mappingResponse.error.message}`);
            reportLines.push('');
            continue;
          }

          effectiveMappingConfigs[mappingSource.entityName] = mappingResponse;

          if (!matchedSheet) {
            issues.push(`No uploaded data sheet could be matched to entity "${mappingSource.entityName}".`);
            reportLines.push('Status: Failed');
            reportLines.push('Issue: No uploaded data sheet matched this entity.');
            reportLines.push('');
            continue;
          }

          usedSheetNames.add(matchedSheet.sheetName);
          computedTotalRecords += sheetData.length;

          if (sheetData.length === 0) {
            issues.push(`Data sheet "${matchedSheet.sheetName}" has no rows to prepare for "${mappingSource.entityName}".`);
            reportLines.push('Status: Failed');
            reportLines.push('Issue: No data rows found.');
            reportLines.push('');
            continue;
          }

          const missingColumns = getMissingMappedColumns(sheetData, mappingResponse);
          if (missingColumns.length > 0) {
            issues.push(`Data sheet "${matchedSheet.sheetName}" is missing mapped columns: ${missingColumns.join(', ')}.`);
            reportLines.push('Status: Failed');
            reportLines.push(`Issue: Missing mapped columns -> ${missingColumns.join(', ')}`);
            reportLines.push('');
            continue;
          }

          computedPassedRecords += sheetData.length;
          reportLines.push('Status: Passed');
          reportLines.push('Issue: Supabase mapping fetched successfully.');
          reportLines.push('');
        }

        setExcelData(effectiveExcelData);
        setMappingConfigs(effectiveMappingConfigs);
        setEntityDataSheetNames(effectiveDataSheetNames);
        setEntityTableNames(effectiveTableNames);
        setDynamicEntities(configuredDatabaseMappings.map(mapping => mapping.entityName));
        setTotalRecords(computedTotalRecords);
        setPassedRecords(computedPassedRecords);
        setValidationReportContent(reportLines.join('\n'));

        if (issues.length > 0) {
          setValidationResult('error');
          setValidationErrors(issues);
        } else {
          setValidationResult('success');
          setValidationErrors([]);
        }

        return;
      }

      const issues: string[] = [];
      const reportLines: string[] = [
        'Validation Report',
        `Workbook: ${file.name}`,
        `Business Object: ${object.label}`,
        '',
      ];

      let computedTotalRecords = 0;
      let computedPassedRecords = 0;
      const effectiveMappingConfigs: Record<string, MappingRule[]> = { ...parsedWorkbook.mappingConfigs };

      parsedWorkbook.entityNames.forEach(entityName => {
        let sheetConfig = parsedWorkbook.mappingConfigs[entityName] || [];
        const sheetData = parsedWorkbook.excelData[entityName] || [];
        const dataSheetName = parsedWorkbook.entityDataSheetNames[entityName];
        let missingColumns = parsedWorkbook.mode === 'mapping'
          ? getMissingMappedColumns(sheetData, sheetConfig)
          : [];

        computedTotalRecords += sheetData.length;

        reportLines.push(`Template Sheet: ${entityName}`);
        reportLines.push(`Data Sheet: ${dataSheetName || 'Not matched'}`);
        reportLines.push(`Rows Found: ${sheetData.length}`);

        if (parsedWorkbook.mode === 'mapping_only') {
          reportLines.push('Status: Passed');
          reportLines.push('Issue: Mapping-only workbook validated successfully. Upload data rows later to use Prepare.');
          reportLines.push('');
          return;
        }

        if (!dataSheetName) {
          issues.push(`Template sheet "${entityName}" could not be matched to a data sheet.`);
          reportLines.push('Status: Failed');
          reportLines.push('Issue: No paired data sheet found.');
          reportLines.push('');
          return;
        }

        if (sheetData.length === 0) {
          issues.push(`Data sheet "${dataSheetName}" has no rows to prepare.`);
          reportLines.push('Status: Failed');
          reportLines.push('Issue: No data rows found.');
          reportLines.push('');
          return;
        }

        if (parsedWorkbook.mode === 'data_only') {
          const autoGeneratedMapping = buildAutoGeneratedMapping(
            entityName,
            sheetData,
            object.autoMappingTemplates ?? [],
          );

          if (!autoGeneratedMapping) {
            computedPassedRecords += sheetData.length;
            reportLines.push('Status: Passed');
            reportLines.push('Issue: No fixed mapping template configured yet. Data validated successfully.');
            reportLines.push('');
            return;
          }

          sheetConfig = autoGeneratedMapping.rules;
          effectiveMappingConfigs[entityName] = autoGeneratedMapping.rules;
          missingColumns = autoGeneratedMapping.missingHeaders;

          if (missingColumns.length > 0) {
            issues.push(`Data sheet "${dataSheetName}" is missing headers for auto-mapping: ${missingColumns.join(', ')}.`);
            reportLines.push('Status: Failed');
            reportLines.push(`Issue: Missing auto-mapping headers -> ${missingColumns.join(', ')}`);
            reportLines.push('');
            return;
          }

          computedPassedRecords += sheetData.length;
          reportLines.push('Status: Passed');
          reportLines.push('Issue: Auto-generated internal mapping from uploaded headers.');
          reportLines.push('');
          return;
        }

        if (missingColumns.length > 0) {
          issues.push(`Data sheet "${dataSheetName}" is missing mapped columns: ${missingColumns.join(', ')}.`);
          reportLines.push('Status: Failed');
          reportLines.push(`Issue: Missing mapped columns -> ${missingColumns.join(', ')}`);
          reportLines.push('');
          return;
        }

        computedPassedRecords += sheetData.length;
        reportLines.push('Status: Passed');
        reportLines.push('Issue: None');
        reportLines.push('');
      });

      setExcelData(parsedWorkbook.excelData);
      setMappingConfigs(effectiveMappingConfigs);
      setEntityDataSheetNames(parsedWorkbook.entityDataSheetNames);
      setEntityTableNames({});
      setDynamicEntities(parsedWorkbook.entityNames);
      setTotalRecords(computedTotalRecords);
      setPassedRecords(computedPassedRecords);
      setValidationReportContent(reportLines.join('\n'));

      if (issues.length > 0) {
        setValidationResult('error');
        setValidationErrors(issues);
      } else {
        setValidationResult('success');
        setValidationErrors([]);
      }
    } catch (err) {
      console.error('Error validating workbook:', err);
      const message = err instanceof Error ? err.message : 'Failed to read the uploaded workbook.';
      setValidationResult('error');
      setValidationErrors([message]);
      setEntityTableNames({});
      setDynamicEntities(getDefaultEntityNames(object));
      setValidationReportContent([
        'Validation Report',
        `Workbook: ${file.name}`,
        '',
        `Issue: ${message}`,
      ].join('\n'));
    } finally {
      setIsValidating(false);
    }
  }, [file, object]);

  const handleDownloadReport = useCallback(() => {
    if (!validationReportContent) {
      toast.error('No validation report is available yet.');
      return;
    }

    const safeObjectName = object.label.toLowerCase().replace(/[^a-z0-9]+/g, '-');
    downloadTextFile(`${safeObjectName}-validation-report.txt`, validationReportContent);
    toast.success('Validation report downloaded successfully.');
  }, [object.label, validationReportContent]);

  const handleDeploy = useCallback(() => {
    setCurrentStep('load');
  }, []);

  const handlePrepare = useCallback(async (id: string, name: string) => {
    const sheetData = excelData[name] || [];
    const sheetConfig = mappingConfigs[name] || [];
    const outputTableName = entityTableNames[name] || name;

    if (sheetConfig.length === 0) {
      toast.error(`No mapping section is configured for sheet: ${name}. Validation can pass in data-only mode, but Prepare needs mapping rows later.`);
      return;
    }

    if (sheetData.length === 0) {
      const dataSheetName = entityDataSheetNames[name];
      toast.error(
        dataSheetName
          ? `No data rows found in sheet: ${dataSheetName}`
          : `No paired data sheet found for template: ${name}`
      );
      return;
    }

    try {
      const datContent = buildDatContent(sheetData, sheetConfig);
      await downloadEntityArchive(outputTableName, datContent);
      setPreparedOutputByEntityId(prev => ({ ...prev, [id]: datContent }));
      setActivePreviewEntityId(id);

      setEntities(prev => prev.map(e => e.id === id ? { ...e, lifecycleState: 'prepared' } : e));
      toast.success(`${outputTableName}.dat packaged and downloaded successfully.`);
    } catch (err) {
      console.error('HDL generation or zipping failed:', err);
      toast.error(`Failed to prepare entity ${name}.`);
    }
  }, [entityDataSheetNames, entityTableNames, excelData, mappingConfigs]);

  const handleSubmit = useCallback((id: string) => {
    setEntities(prev => prev.map(e => e.id === id ? { ...e, lifecycleState: 'submitted' } : e));
    toast.success(`Entity submitted to Oracle HCM Cloud successfully.`);
  }, []);

  const handleViewStatus = useCallback((id: string) => {
    if (!preparedOutputByEntityId[id]) {
      toast.info('Prepare the entity first to preview the generated output.');
      return;
    }

    setActivePreviewEntityId(id);
  }, [preparedOutputByEntityId]);

  const handleReset = useCallback(() => {
    setFile(null);
    setCurrentStep('upload');
    setValidationResult(null);
    setValidationErrors([]);
    setValidationReportContent('');
    setTotalRecords(0);
    setPassedRecords(0);
    setExcelData({});
    setMappingConfigs({});
    setEntityDataSheetNames({});
    setEntityTableNames({});
    setDynamicEntities([]);
    setPreparedOutputByEntityId({});
    setActivePreviewEntityId(null);
    setEntities(createEntitiesFromNames(getDefaultEntityNames(object)));
  }, [object]);

  const ObjectIcon = object.icon;
  const activePreviewEntity = entities.find(entity => entity.id === activePreviewEntityId) ?? null;
  const activePreviewOutput = activePreviewEntityId ? preparedOutputByEntityId[activePreviewEntityId] : null;
  const activePreviewSheetName = activePreviewEntity ? entityDataSheetNames[activePreviewEntity.name] : '';
  const activePreviewTableName = activePreviewEntity ? entityTableNames[activePreviewEntity.name] : '';

  return (
    <div className="animate-in fade-in slide-in-from-right-4 duration-300">
      {/* ── Back + Header ── */}
      <button
        onClick={onBack}
        className="inline-flex items-center gap-2 text-sm font-medium text-slate-500 dark:text-slate-400 hover:text-slate-800 dark:hover:text-white transition-colors mb-5 group"
      >
        <ArrowLeft size={16} className="transition-transform group-hover:-translate-x-1" />
        Back to {module.label}
      </button>

      <div
        className="relative overflow-hidden rounded-2xl mb-8"
        style={{ background: `linear-gradient(135deg, ${module.gradientFrom} 0%, ${module.gradientTo} 100%)` }}
      >
        <div
          className="pointer-events-none absolute -top-20 -right-20 h-64 w-64 rounded-full opacity-20"
          style={{ background: `radial-gradient(circle, ${module.tagColor} 0%, transparent 70%)` }}
        />
        <div
          className="absolute inset-0 opacity-[0.04]"
          style={{
            backgroundImage: `url("data:image/svg+xml,%3Csvg viewBox='0 0 256 256' xmlns='http://www.w3.org/2000/svg'%3E%3Cfilter id='n'%3E%3CfeTurbulence type='fractalNoise' baseFrequency='0.9' numOctaves='4' stitchTiles='stitch'/%3E%3C/filter%3E%3Crect width='100%25' height='100%25' filter='url(%23n)'/%3E%3C/svg%3E")`,
          }}
        />
        <div className="pointer-events-none absolute -bottom-4 -right-4 opacity-10">
          <ObjectIcon size={160} strokeWidth={0.8} className="text-white" />
        </div>
        <div className="relative z-10 px-7 py-7 lg:px-10 lg:py-8">
          <div className="flex items-center gap-4">
            <div
              className="flex h-12 w-12 shrink-0 items-center justify-center rounded-xl"
              style={{ background: 'rgba(255,255,255,0.12)', border: '1px solid rgba(255,255,255,0.2)' }}
            >
              <ObjectIcon size={22} className="text-white" strokeWidth={1.75} />
            </div>
            <div>
              <div
                className="inline-flex items-center gap-1.5 rounded-full px-2.5 py-0.5 text-xs font-semibold mb-1.5 tracking-wide"
                style={{ background: `${module.accentColor}30`, color: module.tagColor }}
              >
                {module.label}
              </div>
              <h1 className="text-xl sm:text-2xl font-bold text-white leading-tight">
                {object.label}
              </h1>
              <p className="mt-1 text-sm text-white/50">{object.description}</p>
            </div>
          </div>
        </div>
      </div>

      {/* ── ETL Stepper ── */}
      <div className="bg-white dark:bg-slate-900/80 border border-slate-200 dark:border-white/10 rounded-xl p-6 mb-6">
        <div className="flex items-center justify-between max-w-[700px] mx-auto">
          {STEPS.map((step, i) => {
            const StepIcon = step.icon;
            const status = i < stepIndex ? 'completed' : i === stepIndex ? 'active' : 'pending';
            return (
              <div key={step.key} className="flex items-center flex-1">
                <div className="flex flex-col items-center">
                  <div
                    className={`w-9 h-9 rounded-full flex items-center justify-center transition-all duration-300 ${
                      status === 'completed'
                        ? 'bg-emerald-600 text-white shadow-md shadow-emerald-600/25'
                        : status === 'active'
                          ? 'bg-white dark:bg-slate-800 border-2 border-emerald-500 text-emerald-600 dark:text-emerald-400 shadow-lg shadow-emerald-500/20'
                          : 'bg-slate-100 dark:bg-slate-800 text-slate-400 dark:text-slate-500'
                    }`}
                  >
                    {status === 'completed' ? <CheckCircle2 size={18} /> : <StepIcon size={16} />}
                  </div>
                  <span className={`text-[11px] mt-2 font-semibold tracking-wide ${
                    status === 'completed'
                      ? 'text-emerald-600 dark:text-emerald-400'
                      : status === 'active'
                        ? 'text-slate-900 dark:text-white'
                        : 'text-slate-400 dark:text-slate-500'
                  }`}>
                    {step.label}
                  </span>
                </div>
                {i < STEPS.length - 1 && (
                  <div className={`flex-1 h-0.5 mx-3 rounded-full transition-colors duration-300 ${
                    i < stepIndex ? 'bg-emerald-500' : 'bg-slate-200 dark:bg-white/10'
                  }`} />
                )}
              </div>
            );
          })}
        </div>
      </div>

      {/* ── Step Content ── */}
      <div className="bg-white dark:bg-slate-900/80 border border-slate-200 dark:border-white/10 rounded-xl overflow-hidden">

        {/* STEP 1: Upload */}
        {currentStep === 'upload' && (
          <div className="p-8">
            <h2 className="text-lg font-semibold text-slate-900 dark:text-white mb-1">
              Upload .xlsx File
            </h2>
            <p className="text-sm text-slate-500 dark:text-slate-400 mb-6">
              Drag and drop your Excel file below, or click to browse. Only <code className="bg-slate-100 dark:bg-slate-800 px-1.5 py-0.5 rounded text-xs font-mono">.xlsx</code> files are accepted.
            </p>

            <div
              onDragOver={handleDragOver}
              onDragLeave={handleDragLeave}
              onDrop={handleDrop}
              onClick={() => fileInputRef.current?.click()}
              className={`relative border-2 border-dashed rounded-xl p-12 text-center cursor-pointer transition-all duration-200 ${
                isDragging
                  ? 'border-emerald-500 bg-emerald-50 dark:bg-emerald-950/20 scale-[1.01]'
                  : file
                    ? 'border-emerald-400 bg-emerald-50/50 dark:bg-emerald-950/10'
                    : 'border-slate-300 dark:border-white/15 hover:border-slate-400 dark:hover:border-white/25 hover:bg-slate-50 dark:hover:bg-white/[0.02]'
              }`}
            >
              <input
                ref={fileInputRef}
                type="file"
                accept=".xlsx"
                onChange={handleFileSelect}
                className="hidden"
              />

              {file ? (
                <div className="flex flex-col items-center gap-3">
                  <div className="flex h-14 w-14 items-center justify-center rounded-xl bg-emerald-100 dark:bg-emerald-900/30">
                    <FileSpreadsheet size={28} className="text-emerald-600 dark:text-emerald-400" />
                  </div>
                  <div>
                    <p className="text-sm font-semibold text-slate-900 dark:text-white">{file.name}</p>
                    <p className="text-xs text-slate-500 dark:text-slate-400 mt-0.5">
                      {(file.size / 1024).toFixed(1)} KB
                    </p>
                  </div>
                  <button
                    onClick={(e) => { e.stopPropagation(); setFile(null); }}
                    className="inline-flex items-center gap-1 text-xs text-red-500 hover:text-red-600 font-medium mt-1"
                  >
                    <X size={12} /> Remove file
                  </button>
                </div>
              ) : (
                <div className="flex flex-col items-center gap-3">
                  <div className="flex h-14 w-14 items-center justify-center rounded-xl bg-slate-100 dark:bg-slate-800">
                    <FileUp size={28} className="text-slate-400 dark:text-slate-500" />
                  </div>
                  <div>
                    <p className="text-sm font-semibold text-slate-700 dark:text-slate-300">
                      Drop your <span style={{ color: module.accentColor }}>.xlsx</span> file here
                    </p>
                    <p className="text-xs text-slate-400 dark:text-slate-500 mt-1">
                      or click to browse from your computer
                    </p>
                  </div>
                </div>
              )}
            </div>

            {file && (
              <div className="flex justify-end mt-6">
                <button
                  onClick={handleValidate}
                  className="inline-flex items-center gap-2 px-5 py-2.5 rounded-lg text-sm font-semibold text-white transition-all duration-200 hover:shadow-lg"
                  style={{ background: module.accentColor }}
                >
                  <CheckCircle2 size={16} />
                  Run Validation
                </button>
              </div>
            )}
          </div>
        )}

        {/* STEP 2: Validate */}
        {currentStep === 'validate' && (
          <div className="p-8">
            <h2 className="text-lg font-semibold text-slate-900 dark:text-white mb-1">
              Data Validation
            </h2>
            <p className="text-sm text-slate-500 dark:text-slate-400 mb-6">
              Checking data integrity, required fields, and format compliance for <strong>{object.label}</strong>.
            </p>

            {isValidating && (
              <div className="flex flex-col items-center py-12 gap-4">
                <Loader2 size={40} className="animate-spin text-emerald-500" />
                <p className="text-sm font-medium text-slate-600 dark:text-slate-300">Validating {file?.name}...</p>
                <div className="w-64 h-1.5 bg-slate-200 dark:bg-slate-700 rounded-full overflow-hidden">
                  <div className="h-full bg-emerald-500 rounded-full animate-pulse" style={{ width: '65%' }} />
                </div>
              </div>
            )}

            {validationResult === 'success' && (
              <div className="rounded-xl border border-emerald-200 dark:border-emerald-800/50 bg-emerald-50 dark:bg-emerald-950/20 p-6">
                <div className="flex items-center gap-3">
                  <div className="flex h-10 w-10 items-center justify-center rounded-full bg-emerald-100 dark:bg-emerald-900/30">
                    <CheckCircle2 size={22} className="text-emerald-600" />
                  </div>
                  <div>
                    <p className="text-sm font-semibold text-emerald-800 dark:text-emerald-300">Validation Passed</p>
                    <p className="text-xs text-emerald-600 dark:text-emerald-400">
                      {successPercentage}% of records passed schema checks. {passedRecords} of {totalRecords} row(s) are ready.
                    </p>
                  </div>
                </div>
                <div className="flex gap-3 mt-6">
                  <button
                    onClick={handleDownloadReport}
                    className="inline-flex items-center gap-2 px-5 py-2.5 rounded-lg text-sm font-semibold text-slate-700 dark:text-slate-300 border border-slate-300 dark:border-white/15 hover:bg-slate-50 dark:hover:bg-white/[0.02] transition-all hover:shadow-md"
                  >
                    <Download size={16} />
                    Download Validation Report
                  </button>
                  <button
                    onClick={handleDeploy}
                    className="inline-flex items-center gap-2 px-5 py-2.5 rounded-lg text-sm font-semibold text-white transition-all hover:shadow-lg"
                    style={{ background: module.accentColor }}
                  >
                    Next
                  </button>
                </div>
              </div>
            )}

            {validationResult === 'error' && (
              <div className="rounded-xl border border-red-200 dark:border-red-800/50 bg-red-50 dark:bg-red-950/20 p-6">
                <div className="flex items-center gap-3 mb-4">
                  <div className="flex h-10 w-10 items-center justify-center rounded-full bg-red-100 dark:bg-red-900/30">
                    <AlertCircle size={22} className="text-red-600" />
                  </div>
                  <div>
                    <p className="text-sm font-semibold text-red-800 dark:text-red-300">Validation Failed</p>
                    <p className="text-xs text-red-600 dark:text-red-400">{validationErrors.length} validation issue(s) found. Fix and re-upload.</p>
                  </div>
                </div>
                <ul className="space-y-2 mb-6">
                  {validationErrors.map((err, i) => (
                    <li key={i} className="flex items-start gap-2 text-sm text-red-700 dark:text-red-300">
                      <AlertCircle size={14} className="mt-0.5 shrink-0" />
                      {err}
                    </li>
                  ))}
                </ul>
                <button
                  onClick={handleReset}
                  className="inline-flex items-center gap-2 px-4 py-2 rounded-lg text-sm font-medium text-red-700 dark:text-red-300 border border-red-300 dark:border-red-700 hover:bg-red-100 dark:hover:bg-red-900/30 transition-colors"
                >
                  <Upload size={14} />
                  Re-Upload File
                </button>
              </div>
            )}
          </div>
        )}



        {/* STEP 3: Load to Oracle (Entity Lifecycle Management) */}
        {currentStep === 'load' && (
          <div className="p-8">
            <div className="flex justify-between items-center mb-6">
              <div>
                <h2 className="text-xl font-bold text-slate-900 dark:text-white leading-tight">
                  Deploy & Load to Oracle Cloud
                </h2>
                <p className="text-sm text-slate-500 dark:text-slate-400 mt-1">
                  Perform granular lifecycle management for all target HCM entities.
                </p>
              </div>
              <button
                onClick={handleReset}
                className="inline-flex items-center gap-2 px-4 py-2 rounded-lg text-sm font-semibold border border-slate-200 dark:border-white/10 text-slate-700 dark:text-slate-300 hover:bg-slate-50 dark:hover:bg-slate-800/50 transition-all hover:shadow-sm"
              >
                <Upload size={14} />
                Upload Another File
              </button>
            </div>

            <div className="bg-white dark:bg-slate-950 border border-slate-200 dark:border-white/10 rounded-xl p-6 shadow-sm">
              <div className="flex flex-col gap-4 border-b border-slate-100 dark:border-white/5 pb-4 mb-4">
                <div>
                  <h3 className="text-lg font-bold text-slate-900 dark:text-white">
                    {object.loadTitle ?? object.label}
                  </h3>
                  <div className="mt-2 inline-flex items-start gap-2.5 text-xs text-amber-700 dark:text-amber-400 bg-amber-50 dark:bg-amber-950/20 border border-amber-200/50 dark:border-amber-800/30 rounded-lg p-3 max-w-[650px] leading-relaxed">
                    <AlertCircle size={16} className="mt-0.5 shrink-0 text-amber-600 dark:text-amber-500" />
                    <span>
                      {object.loadInstructions ?? 'Manage the HCM Data Loader lifecycle for each entity. Please load the objects in the displayed order to prevent data dependency errors.'}
                    </span>
                  </div>
                </div>
              </div>

              <div className="space-y-1">
                {entities.map((entity, index) => {
                  const isPending = entity.lifecycleState === 'pending';
                  const isPrepared = entity.lifecycleState === 'prepared';
                  const isSubmitted = entity.lifecycleState === 'submitted';
                  const matchedDataSheetName = entityDataSheetNames[entity.name];
                  const matchedRowCount = excelData[entity.name]?.length ?? 0;
                  const mappingTableName = entityTableNames[entity.name];

                  return (
                    <div
                      key={entity.id}
                      className="flex justify-between items-center py-4 border-b border-slate-100 dark:border-white/5 last:border-0 hover:bg-slate-50 dark:hover:bg-white/[0.01] px-4 rounded-lg transition-colors animate-fade-in"
                    >
                      {/* Left Side: Index + Name */}
                      <div className="flex items-center gap-3">
                        <span className="text-sm font-mono text-slate-400 dark:text-slate-500">
                          {(index + 1).toString().padStart(2, '0')}
                        </span>
                        <div>
                          <span className="font-semibold text-slate-800 dark:text-slate-200">
                            {entity.name}
                          </span>
                          <p className="mt-1 text-xs text-slate-500 dark:text-slate-400">
                            {matchedDataSheetName
                              ? `${mappingTableName ? `Table: ${mappingTableName} | ` : ''}Data sheet: ${matchedDataSheetName} | Rows found: ${matchedRowCount}`
                              : 'No data sheet matched yet'}
                          </p>
                        </div>
                      </div>

                      {/* Right Side: Button Group */}
                      <div className="flex items-center gap-3">
                        {/* Prepare Button */}
                        <button
                          onClick={() => handlePrepare(entity.id, entity.name)}
                          disabled={!isPending}
                          className={`inline-flex items-center gap-1.5 px-3 py-1.5 rounded-lg text-xs font-semibold border transition-all duration-200 ${
                            isPending
                              ? 'border-slate-300 dark:border-white/15 text-slate-700 dark:text-slate-300 hover:bg-slate-50 dark:hover:bg-slate-800/50 shadow-sm'
                              : 'border-emerald-200/50 bg-emerald-500/10 text-emerald-600 dark:text-emerald-400 cursor-default'
                          }`}
                        >
                          {isPending ? (
                            'Prepare'
                          ) : (
                            <>
                              <CheckCircle2 size={12} />
                              Prepared
                            </>
                          )}
                        </button>

                        {/* Submit Button */}
                        <button
                          onClick={() => handleSubmit(entity.id)}
                          disabled={!isPrepared}
                          className={`inline-flex items-center gap-1.5 px-3 py-1.5 rounded-lg text-xs font-semibold transition-all duration-200 ${
                            isPrepared
                              ? 'text-white shadow-md shadow-emerald-500/20 hover:brightness-110'
                              : isSubmitted
                                ? 'bg-slate-100 dark:bg-slate-800 text-slate-400 dark:text-slate-500 cursor-default'
                                : 'bg-slate-100 dark:bg-slate-800 text-slate-400 dark:text-slate-500 cursor-not-allowed'
                          }`}
                          style={{
                            background: isPrepared ? module.accentColor : undefined,
                          }}
                        >
                          {isSubmitted ? 'Submitted' : 'Submit'}
                        </button>

                        {/* Status Button/Badge */}
                        <button
                          onClick={() => handleViewStatus(entity.id)}
                          className={`inline-flex items-center gap-1 px-3 py-1.5 rounded-lg text-xs font-semibold transition-colors duration-200 ${
                            isSubmitted
                              ? 'bg-emerald-50 dark:bg-emerald-950/20 text-emerald-700 dark:text-emerald-400 hover:bg-emerald-100 dark:hover:bg-emerald-900/30'
                              : isPrepared
                                ? 'bg-blue-50 dark:bg-blue-950/20 text-blue-700 dark:text-blue-400 hover:bg-blue-100 dark:hover:bg-blue-900/30'
                                : 'bg-slate-100 dark:bg-slate-800 text-slate-500 dark:text-slate-400 hover:bg-slate-200 dark:hover:bg-slate-700/50'
                          }`}
                        >
                          <span>Preview Output</span>
                        </button>
                      </div>
                    </div>
                  );
                })}
              </div>

              {activePreviewEntity && activePreviewOutput !== null && activePreviewOutput !== undefined && (
                <div className="mt-6 rounded-xl border border-slate-200 dark:border-white/10 bg-slate-50 dark:bg-slate-900/60 overflow-hidden">
                  <div className="flex flex-col gap-2 border-b border-slate-200 dark:border-white/10 px-5 py-4 sm:flex-row sm:items-center sm:justify-between">
                    <div>
                      <div className="inline-flex items-center gap-2 text-sm font-semibold text-slate-900 dark:text-white">
                        <FileText size={16} className="text-emerald-600 dark:text-emerald-400" />
                        Generated DAT Preview
                      </div>
                      <p className="mt-1 text-xs text-slate-500 dark:text-slate-400">
                        Entity: <span className="font-medium text-slate-700 dark:text-slate-300">{activePreviewEntity.name}</span>
                        {activePreviewTableName ? (
                          <>
                            {' '}| Table: <span className="font-medium text-slate-700 dark:text-slate-300">{activePreviewTableName}</span>
                          </>
                        ) : null}
                        {activePreviewSheetName ? (
                          <>
                            {' '}| Data sheet: <span className="font-medium text-slate-700 dark:text-slate-300">{activePreviewSheetName}</span>
                          </>
                        ) : null}
                      </p>
                    </div>
                    <div className="text-xs text-emerald-700 dark:text-emerald-400 font-medium">
                      Excel values mapped into HDL output
                    </div>
                  </div>
                  <pre className="max-h-[320px] overflow-auto px-5 py-4 text-xs leading-6 text-slate-800 dark:text-slate-200 bg-white dark:bg-slate-950 whitespace-pre-wrap break-all">
                    {activePreviewOutput.trim() ? activePreviewOutput : 'No DAT lines were generated for this sheet.'}
                  </pre>
                </div>
              )}
            </div>
          </div>
        )}
      </div>
    </div>
  );
}
